### ISSUE TITLE
Crypto extentions

### ISSUE THREAD

**Issue by aledolme** [asdfjkl/pyky#2]
Good morning. 
I was trying to compile your code, but I am encountering some problems with Crypto extensions. I have downloaded the crypto extension and changed each python file call of this extension with "crypto" instead of Crypto because otherwise Visual Studio was not able to find it. 
Despite so, each time I try to run the code it is stuck in the "prf.py" file, reporting an error that it cannot find the "Crypto" module. 

Any suggestions on how to solve the problem? PyCrypto package installation is no working because of a legacy-install-failure. 

Thanks you

**Comment by asdfjkl** [comment]
`pip install pycryptodome`. You need that one (or pycryptodomex), as PyCrypto is outdated.
