### ISSUE TITLE
What version of reference code is used?

### ISSUE THREAD

**Issue by lizhirui** [asdfjkl/pyky#4]
I notices that  zetas and zetas_inv are all used in ntt.py, but there is only one zetas array(no zetas_inv) in latest reference code(master and round3 branch, github.com/pq-crystals/kyber). But there are zetas and zetas_inv arrarys in ntt.c of round 2 branch.

So, what version of reference code is used in your code?

**Comment by asdfjkl** [comment]
I can't remember precisely, but I think they reworked the NTT transform in this commit https://github.com/pq-crystals/kyber/commit/b0ec8453c41ed869aad85ed1d1228a7792236a51
As you can see, the inverted zeta array was deleted in that commit...

**Comment by lizhirui** [comment]
OK, Thank you.
